### ISSUE TITLE
Broken with minecraft-protocol 0.16, missing protocol property

### ISSUE THREAD

**Issue by deathcap** [deathcap/wsmc#19]
Using the latest releases minecraft-protocol 0.16.5 and mineflayer 1.5.3, wsmc fails with:

```
node wsmc.js 
wsmc/wsmc.js:4
var readVarInt = minecraft_protocol.protocol.types.varint[0];
                                            ^

TypeError: Cannot read property 'types' of undefined
    at Object.<anonymous> (wsmc/wsmc.js:4:45)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3
```

**Comment by deathcap** [comment]
Works with minecraft-protocol@0.13.4, fails with minecraft-protocol@0.14.0

**Comment by deathcap** [comment]
Began to update to 0.15.0 on https://github.com/deathcap/wsmc/compare/nmp0.15.0 - but `node examples/mcwebchat/mcwebchat.js` fails with this mysterious error:

```
wsmc/node_modules/prismarine-block/index.js:5
  var mcData=require('minecraft-data')(mcVersion);
                                      ^

TypeError: require(...) is not a function
    at loader (wsmc/node_modules/prismarine-block/index.js:5:39)
    at Object.<anonymous> (wsmc/node_modules/mineflayer/lib/plugins/blocks.js:5:40)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (wsmc/mineflayer-stream.js:11:15)
    at Module._compile (module.js:398:26)
```

Probably ought to just update straight to minecraft-protocol 0.16.0. But what version specifier should I use for API compatibility with this module? ^0.15.0 would pickup ^0.16.0. since "^" only locks the major version, accepts changes minor and patch - it may be acceptable to use ~0.15.0, to lock major and minor, only allowing updates from the patch version number. Or stricter, '0.15.0' (or 0.16.5, etc.) to lock to an exact version.

**Comment by deathcap** [comment]
Caused by ancient minecraft-data (0.0.1), updated to ~0.16.3, fixed above 'is not a function' error with minecraft-data but now hitting an incompatibility with mineflayer (1.5.3):

```
$ node examples/mcwebchat/mcwebchat.js 
You are using a pure-javascript implementation of RSA.
Your performance might be subpar. Please consider installing URSA
module.js:328
    throw err;
    ^

Error: Cannot find module 'mineflayer/lib/block'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (wsmc/mineflayer-stream.js:41:10)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
```

**Comment by deathcap** [comment]
Starting update to minecraft-protocol 0.16.6, failure on nmp0.15.0 branch is:

```
wsmc/wsmc.js:4
var readVarInt = minecraft_protocol.types.varint[0];
                                         ^

TypeError: Cannot read property 'varint' of undefined
    at Object.<anonymous> (wsmc/wsmc.js:4:42)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

major change is move to use protodef, relevant commit: https://github.com/PrismarineJS/node-minecraft-protocol/commit/f45c6dff49cbc12903ac2c1b9d408e23d029c290

**Comment by deathcap** [comment]
wsmc/JavaScript server now runs, but the mcwebchat example (browserified) fails in a dynamic require:

```
        function mcVersionToMcData(mcVersion) // mcVersion = '1.8'
        {
            var dir = "./minecraft-data/" + mcVersion;
            return {
                blocks: require(dir + '/enums/blocks'),

```

since browserify compiles requires statically, unable to resolve at runtime:

require('./minecraft-data/1.8/enums/blocks')
Error: Cannot find module './minecraft-data/1.8/enums/blocks'

**Comment by deathcap** [comment]
Added brfs transform but now running into https://github.com/rom1504/node-mojangson browserify incompatibility

```
 mcwebchat@0.0.1 start wsmc/examples/mcwebchat
> wzrd mcwebchat.js:bundle.js -- --global-transform brfs

server started at http://localhost:9966
{"url":"/bundle.js","type":"bundle","command":"browserify mcwebchat.js --global-transform brfs","elapsed":"1609ms","time":"2016-01-09T19:59:38.656Z"}
TypeError: callee.apply is not a function while parsing file: mineflayer/node_modules/node-mojangson/grammar.js
    at walk (wsmc/examples/mcwebchat/node_modules/brfs/node_modules/static-module/node_modules/static-eval/index.js:89:27)
    at walk (wsmc/examples/mcwebchat/node_modules/brfs/node_modules/static-module/node_modules/static-eval/index.js:92:23)
    at walk (wsmc/examples/mcwebchat/node_modules/brfs/node_modules/static-module/node_modules/static-eval/index.js:77:26)
    at walk (wsmc/examples/mcwebchat/node_modules/brfs/node_modules/static-module/node_modules/static-eval/index.js:85:25)
    at module.exports (wsmc/examples/mcwebchat/node_modules/brfs/node_modules/static-module/node_modules/static-eval/index.js:114:7)
    at traverse (wsmc/examples/mcwebchat/node_modules/brfs/node_modules/static-module/index.js:256:23)
    at walk (wsmc/examples/mcwebchat/node_modules/brfs/node_modules/static-module/index.js:208:13)
    at walk (wsmc/examples/mcwebchat/node_modules/brfs/node_modules/static-module/node_modules/falafel/index.js:49:9)
    at wsmc/examples/mcwebchat/node_modules/brfs/node_modules/static-module/node_modules/falafel/index.js:46:17
    at forEach (wsmc/examples/mcwebchat/node_modules/brfs/node_modules/static-module/node_modules/falafel/node_modules/foreach/index.js:12:16)
    at walk (wsmc/examples/mcwebchat/node_modules/brfs/node_modules/static-module/node_modules/falafel/index.js:34:9)

````

**Comment by deathcap** [comment]
mojangson 0.2.2 is in mineflayer 2570e20, testing with it able to brfs global transform now with no parse error - but the transformed [requireindex](https://www.npmjs.com/package/requireindex) crashes here:

              var files = FS.readdirSync(dir);

with no defined 'FS' (?) - this likely cannot be statically replaced. But mineflayer has had:

            var plugins = requireIndex(path.join(__dirname, 'lib', 'plugins'));

for a while, since at least https://github.com/PrismarineJS/mineflayer/commit/bd4eba1765bcc94e1f5cfd489f10a29d28c91849 - not sure how I had this working in browserify previously

**Comment by deathcap** [comment]
Mineflayer plugins were statically require()'d in wsmc/mineflayer-stream.js: https://github.com/deathcap/wsmc/blob/57ceb6a6fa9c7f637daf9f62bcfd5b1e1fefa02b/mineflayer-stream.js#L8-L31 - this plugin list (via the dynamic requireIndex) wasn't supposed to be used, but require('mineflayer') is called from the change to use require('mineflayer').Block (etc.) instead of require('mineflayer/lib/block') I had to in order to get prismarine-block: https://github.com/deathcap/wsmc/commit/d94181283b588b127269d1aed90d5d40d9964915

This puts browserified mineflayer in a bit of a pickle:

* I can't change back to require('mineflayer/lib/block') because block.js no longer exists in mineflayer (and neither does biome.js): https://github.com/PrismarineJS/mineflayer/tree/master/lib - they were moved to separate modules: https://github.com/PrismarineJS/mineflayer/commit/ca365c3c1bbdb39cf6632b71e7f3d6363d36c2ae - prismarine-block and prismarine-biome. 
* If I change to require('mineflayer').Block to require("prismarine-block")(mc.minecraftVersion) (and likewise for biome), I'll have to include prismarine-block in my project, and ensure it matches the same version as mineflayer uses. If other objects move to their own modules, then I'll have to update my project to the new modules accordingly, increasing maintenance difficulty and version fragility.
* If I use require('mineflayer').Block then mineflayer/index.js will execute and hit the unbrowserifiable requireindex (maybe it only worked before due https://github.com/substack/static-eval/issues/10 Doesn't handle var statements with multiple declarations?)

I think any solution will require changes to mineflayer, but I'm not sure what is the correct fix going forward.

**Comment by deathcap** [comment]
After solving the above issue, next step is to update wsmc/minecraft-protocol-stream.js for the changes in node-minecraft-protocol/createClient.js.

**Comment by deathcap** [comment]
Current status: wsmc runs, but on ws connection, logs a bunch of errors (probably not transitioning states correctly — the ws is supposed to mainly be in the PLAY state):

```
Successfully connected to MC
compress { threshold: 256 }
Skipping state [object Object] packet:  <Buffer 03 80 02>
Skipping state [object Object] packet:  <Buffer 02 24 34 34 63 63 61 36 61 34 2d 34 30 36 65 2d 33 38 36 36 2d 39 35 63 64 2d 64 34 63 65 38 33 64 62 38 34 63 61 09 77 65 62 75 73 65 72 2d 36>
…
```

no chat messages received, attempting to send a message in mcwebchat fails with:

WebSocket error: Error: Serialization error for .toServer : SizeOf error for name : chat is not in the mappings value

stack trace points to ProtoDef but doesn't say where it is called:

exception.stack
"Error: Serialization error for .toServer : SizeOf error for name : chat is not in the mappings value
    at ProtoDef.sizeOfMapper (http://localhost:9966/bundle.js:95584:34)
    at ProtoDef.sizeOf (http://localhost:9966/bundle.js:95985:33)
    at http://localhost:9966/bundle.js:95484:21
    at tryCatch (http://localhost:9966/bundle.js:96077:12)
    at tryDoc (http://localhost:9966/bundle.js:96084:10)
    at http://localhost:9966/bundle.js:95483:19
    at Array.reduce (native)
    at ProtoDef.sizeOfContainer (http://localhost:9966/bundle.js:95479:23)
    at ProtoDef.sizeOf (http://localhost:9966/bundle.js:95892:65)
    at ProtoDef.sizeOf (http://localhost:9966/bundle.js:95985:33)"

**Comment by rom1504** [comment]
"chat is not in the mappings value" means it's not in the correct state indeed. That error definitely doesn't say enough though.

**Comment by rom1504** [comment]
I think that's happening somewhere you do a .write('chat',...) and you are not in PLAY state.

**Comment by deathcap** [comment]
It's throwing the exception here:

<img width="855" alt="screen shot 2016-01-12 at 10 27 51 pm" src="https://cloud.githubusercontent.com/assets/5897956/12286741/ca2614ac-b97b-11e5-962f-27a7c7f2944c.png">

**Comment by deathcap** [comment]
Tracking further updates in the pull request: https://github.com/deathcap/wsmc/pull/21

**Comment by deathcap** [comment]
Fixed in https://github.com/deathcap/wsmc/pull/21
